// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_7CG7x-jUI2JCtaNg-VJDj8vQTwlcrgc',
    appId: '1:474600304129:web:e240ab039aed371c961a00',
    messagingSenderId: '474600304129',
    projectId: 'pos-app-a61fd',
    authDomain: 'pos-app-a61fd.firebaseapp.com',
    storageBucket: 'pos-app-a61fd.firebasestorage.app',
    measurementId: 'G-HVHRJQ2B9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADr1Hla3oO1GERWT6sHZkaVigAlU1vLfQ',
    appId: '1:474600304129:android:8d8ba75b1f074f2d961a00',
    messagingSenderId: '474600304129',
    projectId: 'pos-app-a61fd',
    storageBucket: 'pos-app-a61fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4Ioah8gq9xiPtp2837_9V061fgf_yvhg',
    appId: '1:474600304129:ios:eca77de37395eb27961a00',
    messagingSenderId: '474600304129',
    projectId: 'pos-app-a61fd',
    storageBucket: 'pos-app-a61fd.firebasestorage.app',
    iosBundleId: 'com.example.posApp',
  );
}
